// <auto-generated />
using ApiForMignightMotorist.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiForMignightMotorist.Migrations
{
    [DbContext(typeof(ContextDb))]
    partial class ContextDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ApiForMignightMotorist.Models.Logins", b =>
                {
                    b.Property<int>("IdLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdLogin");

                    b.HasIndex("IdUser");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("ApiForMignightMotorist.Models.Scins", b =>
                {
                    b.Property<int>("IdScin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameScin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdScin");

                    b.ToTable("Scins");
                });

            modelBuilder.Entity("ApiForMignightMotorist.Models.UserScins", b =>
                {
                    b.Property<int>("IdUserScins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdScin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUserScins");

                    b.HasIndex("IdScin");

                    b.HasIndex("IdUser");

                    b.ToTable("UserScins");
                });

            modelBuilder.Entity("ApiForMignightMotorist.Models.Users", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedScin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApiForMignightMotorist.Models.Logins", b =>
                {
                    b.HasOne("ApiForMignightMotorist.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ApiForMignightMotorist.Models.UserScins", b =>
                {
                    b.HasOne("ApiForMignightMotorist.Models.Scins", "Scins")
                        .WithMany()
                        .HasForeignKey("IdScin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiForMignightMotorist.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scins");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
